version: '2'
services:
    solr:
        image: ebispot/ols-solr:latest
        environment:
          - SOLR_HOME=/mnt/solr-config
        ports:
          - 8983:8983
        volumes:
          - ols-solr-data:/var/solr
          - ./ols-solr/src/main/solr-5-config:/mnt/solr-config
        command: ["-Dsolr.solr.home=/mnt/solr-config", "-Dsolr.data.dir=/var/solr", "-f"]
    mongo:
      image: mongo:3.2.9
      ports:
          - 27017:27017
      volumes:
          - ols-mongo-data:/data/db
      command:
          - mongod
    ols-web:
      build:
          context: .
          dockerfile: ols-web/Dockerfile
      depends_on:
        - solr
        - mongo
      links:
        - solr
        - mongo
      environment:
        - spring.data.solr.host=http://solr:8983/solr
        - spring.data.mongodb.host=mongo
        - OLS_HOME=/mnt/
      volumes:
        - ols-neo4j-data:/mnt/neo4j 
      ports:
      - 8080:8080
volumes:
    ols-solr-data:
        external: true
    ols-mongo-data:
        external: true
    ols-neo4j-data:
        external: true

