"@context":

ontologies:

## EFO

  - id: efo
    preferredPrefix: EFO
    title: Experimental Factor Ontology
    uri: http://www.ebi.ac.uk/efo
    description: "The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases, and for external projects such as the NHGRI GWAS catalogue. It combines parts of several biological ontologies, such as anatomy, disease and chemical compounds. The scope of EFO is to support the annotation, analysis and visualization of data handled by many groups at the EBI and as the core ontology for the Centre for Therapeutic Validation (CTTV)"
    homepage: http://www.ebi.ac.uk/efo
    mailing_list: efo-users@lists.sourceforge.net
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    base_uri:
      - http://www.ebi.ac.uk/efo/EFO_
    reasoner: OWL2
    oboSlims: false
    ontology_purl : http://www.ebi.ac.uk/efo/efo.owl


## ORDO

  - id: ordo
    preferredPrefix: ORDO
    description: "The Orphanet Rare Disease ontology (ORDO) is jointly developed by Orphanet and the EBI to provide a structured vocabulary for rare diseases capturing relationships between diseases, genes and other relevant features which will form a useful resource for the computational analysis of rare diseases.
                  It derived from the Orphanet database (www.orpha.net ) , a multilingual database dedicated to rare diseases populated from literature and validated by international experts.
                  It integrates a nosology (classification of rare diseases), relationships (gene-disease relations, epiemological data) and connections with other terminologies (MeSH, UMLS, MedDRA),databases (OMIM, UniProtKB, HGNC, ensembl, Reactome, IUPHAR, Geantlas) or classifications (ICD10)."
    title: Orphanet Rare Disease Ontolog
    uri: http://www.orpha.net/ontology/orphanet.owl
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://www.orpha.net/ORDO/Orphanet_
    reasoner: OWL2
    oboSlims: false
    ontology_purl : http://www.orphadata.org/data/ORDO/ordo_orphanet.owl

## TEDDY

  - id: teddy
    preferredPrefix: TEDDY
    description: "TEDDY is an ontology for dynamical behaviours, observable dynamical phenomena, and control elements of bio-models and biological systems in Systems and Synthetic Biology."
    title: "Terminology for Description of Dynamics"
    uri: http://identifiers.org/teddy/
    definition_property:
      - http://www.w3.org/2004/02/skos/core#definition
    synonym_property:
      - http://www.w3.org/2004/02/skos/core#altLabel
    base_uri:
      - http://identifiers.org/teddy/TEDDY_
    oboSlims: false
    ontology_purl : http://www.biomodels.net/teddy/TEDDY

## EDAM

  - id: edam
    preferredPrefix: EDAM
    title: EDAM bioinformatics ontology
    uri: http://edamontology.org
    description: "EDAM is a simple ontology of well established, familiar concepts that are prevalent within bioinformatics, including types of data and data identifiers, data formats, operations and topics. EDAM provides a set of terms with synonyms and definitions - organised into an intuitive hierarchy for convenient use."
    homepage: http://edamontology.org
    mailing_list: edam@elixir-dk.org
    definition_property:
      - http://www.geneontology.org/formats/oboInOwl#hasDefinition
    synonym_property:
     - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    base_uri:
      - http://edamontology.org/data_
      - http://edamontology.org/identifier_
      - http://edamontology.org/topic_
      - http://edamontology.org/format_
    oboSlims: false
    ontology_purl : http://edamontology.org/EDAM.owl   ### This is the download URL

## CCO

  - id: cco
    preferredPrefix: CCO
    title: Cell Cycle Ontology
    uri: http://purl.obolibrary.org/obo/cco
    description: "The Cell Cycle Ontology extends existing ontologies for cell cycle knowledge building a resource that integrates and manages knowledge about the cell cycle components and regulatory aspects."
    homepage: http://www.semantic-systems-biology.org/apo
    mailing_list: vladimir.n.mironov@gmail.com
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    base_uri:
      - http://purl.obolibrary.org/obo/CCO_
    oboSlims: true
    ontology_purl : http://www.bio.ntnu.no/ontology/CCO/cco.owl   ### This is the download URL

## CMPO

  - id: cmpo
    preferredPrefix: CMPO
    title: Cellular Microscopy Phenotype Ontology
    uri: http://www.ebi.ac.uk/cmpo
    description: "CMPO is a species neutral ontology for describing general phenotypic observations relating to the whole cell, cellular components, cellular processes and cell populations."
    homepage: http://www.ebi.ac.uk/cmpo
    mailing_list: jupp@ebi.ac.uk
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    base_uri:
      - http://www.ebi.ac.uk/cmpo/CMPO_
    oboSlims: true
    reasoner: EL
    ontology_purl : http://www.ebi.ac.uk/cmpo/cmpo.owl  ### This is the download URL

## eNanoMapper

  - id: enm
    preferredPrefix: ENM
    title: eNanoMapper Ontology
    uri: http://purl.enanomapper.org/onto/enanomapper.owl
    description: "The eNanoMapper project (www.enanomapper.net) is creating a pan-European computational infrastructure for toxicological data management for ENMs, based on semantic web standards and ontologies. > This ontology is an application ontology targeting the f\
ull domain of nanomaterial safety assessment. It re-uses several other ontologies including the NPO, CHEMINF, ChEBI, and ENVO. "
    homepage: http://www.enanomapper.net/
    mailing_list: https://github.com/enanomapper/ontologies
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
      - http://purl.obolibrary.org/obo/IAO_0000115
      - http://purl.bioontology.org/ontology/npo#definition
      - http://purl.obolibrary.org/obo#Definition
      - http://purl.org/dc/elements/1.1/description
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
      - http://purl.obolibrary.org/obo/IAO_0000118
    hierarchical_property:
      - http://www.bioassayontology.org/bao#BAO_0090002
      - http://purl.bioontology.org/ontology/npo#part_of
    base_uri:
      - http://purl.enanomapper.org/onto/ENM_
    oboSlims: false
    ontology_purl : http://purl.enanomapper.net/onto/enanomapper.owl

## ATOL

  - id: atol
    preferredPrefix: ATOL
    title: Animal Trait Ontology for Livestock
    uri: file:/C:/Lea/ontologies/versions%20ATOL/atol_v3.0.obo
    description: "ATOL (Animal Trait Ontology for Livestock) is an ontology of characteristics defining phenotypes of livestock in their environment (EOL). ATOL aims to: - provide a reference ontology of phenotypic traits of farm animals for the international scientific\
 and educational - communities, farmers, etc.; - deliver this reference ontology in a language which can be used by computers in order to support database management, semantic analysis and modeling; - represent traits as generic as possible for livestock vertebrates; - \
make the ATOL ontology as operational as possible and closely related to measurement techniques; - structure the ontology in relation to animal production."
    homepage: http://www.atol-ontology.com
    mailing_list: pylebail@rennes.inra.fr
    definition_property:
      - "file:/C:/Lea/ontologies/versions%20ATOL/atol_v3.0.obo#definition"
    synonym_property:
      - "file:/C:/Lea/ontologies/versions%20ATOL/atol_v3.0.obo#synonymExact"
    base_uri:
      - http://purl.org/obo/owlATOL_
    oboSlims: false
    ontology_purl : http://www.atol-ontology.com/public/telechargement/atol_v6.owl

## EOL

  - id: eol
    preferredPrefix: EOL
    title: Environment Ontology for Livestock
    uri: file:/C:/Lea/ontologies/environnement/leo.obo
    description: "L'ontologie EOL décrit les conditions d'environnement des élevages d'animaux domestiques. Elle décrit plus particulièrement les modalités de l'alimentation, de l'environnement, de la structure des élevages et des systèmes d'élevage"
    homepage: http://www.atol-ontology.com
    mailing_list: pylebail@rennes.inra.fr
    definition_property:
      - "file:/C:/Lea/ontologies/environnement/leo.obo#definition"
    synonym_property:
      - "file:/C:/Lea/ontologies/environnement/leo.obo#synonymExact"
    base_uri:
      - http://purl.org/obo/owlEOL_
    ontology_purl : http://www.atol-ontology.com/ontology/20082013/eol_v4__collaboration.owl

## LBO

  - id: lbo
    preferredPrefix: LBO
    title: Livestock Breed Ontology
    uri: http://purl.obolibrary.org/obo/lbo
    description: "A vocabulary for cattle, chicken, horse, pig, and sheep breeds."
    homepage: http://bioportal.bioontology.org/ontologies/LBO
    mailing_list: jreecy@iastate.edu
    definition_property:
      - "file:/C:/Lea/ontologies/environnement/leo.obo#definition"
    synonym_property:
      - "file:/C:/Lea/ontologies/environnement/leo.obo#synonymExact"
    base_uri:
      - http://purl.org/obo/owlEOL_
    oboSlims: false
    ontology_purl : http://data.bioontology.org/ontologies/LBO/submissions/2/download?apikey=0911d614-1dd4-41c0-afd4-9f3df0fc70be


## AncestrO

  - id: ancestro
    preferredPrefix: ancestro
    title: Ancestry Ontology
    uri: http://www.ebi.ac.uk/ancestro
    description: "The Ancestry Ontology (Ancestro) provides a systematic description of the ancestry concepts used in the NHGRI-EBI Catalog of published genome-wide association studies. It includes a list of countries, regions and major areas (essentially continents), as well as a fairly exhaustive list of country- or region-specific ancestral groups, uncategorised ancestral groups and population isolates."
    homepage: https://github.com/EBISPOT/ancestro/
    mailing_list:
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://purl.obolibrary.org/obo/IAO_0000118
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://www.ebi.ac.uk/ancestro/ancestro_
    oboSlims: false
    reasoner: OWL2
    ontology_purl : https://raw.githubusercontent.com/EBISPOT/ancestro/master/ancestro.owl

## GAZ overide

  - id: gaz
    is_foundry: true
    ontology_purl: http://purl.obolibrary.org/obo/gaz.obo
    reasoner: EL
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0001025
      - http://purl.obolibrary.org/obo/RO_0002151
      - http://purl.obolibrary.org/obo/RO_0002376
      - http://purl.obolibrary.org/obo/RO_0002377
      - http://purl.obolibrary.org/obo/UBREL_0000001
      - http://purl.obolibrary.org/obo/RO_0002219
      - http://purl.obolibrary.org/obo/RO_0002379
      - http://purl.obolibrary.org/obo/RO_0002378
      - http://purl.obolibrary.org/obo/RO_0002090
      - http://purl.obolibrary.org/obo/TEMP#proper_partof
      - http://purl.obolibrary.org/obo/TEMP#overlapped_by
      - http://purl.obolibrary.org/obo/RO_0002131
      - http://purl.obolibrary.org/obo/RO_0002220

## BTO overide

  - id: bto
    is_foundry: true
    ontology_purl: http://purl.obolibrary.org/obo/bto.owl
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/bto#develops_from
      - http://purl.obolibrary.org/obo/bto#related_to

## ProbOnto

  - id: probonto
    preferredPrefix: probonto
    title: Probability Ontology test
    uri: http://www.probonto.org/ontology
    description: "ProbOnto, is an ontology-based knowledge base of probability distributions, featuring more than eighty uni- and multivariate distributions with their defining functions, characteristics, relationships and reparameterisation formulas."
    homepage: http://probonto.org
    mailing_list: probonto.dev@gmail.com
    definition_property:
      - http://www.probonto.org/core#0000028
    base_uri:
      - http://www.probonto.org/core
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/probonto/ontology/master/probonto4ols.owl


## PRIDE ontology

  - id: pride
    preferredPrefix: PRIDE
    title: PRIDE Controlled Vocabulary
    uri: http://purl.obolibrary.org/obo/pride_cv.obo
    description: "The PRIDE PRoteomics IDEntifications (PRIDE) database is a centralized, standards compliant, public data repository for proteomics data, including protein and peptide identifications, post-translational modifications and supporting spectral evidence."
    homepage: https://github.com/PRIDE-Utilities/pride-ontology
    mailing_list: https://github.com/PRIDE-Utilities/pride-ontology/issues
    definition_property:
      - http://purl.obolibrary.org/obo/def
    synonym_property:
      - http://www.geneontology.org/formats/oboInOWL#hasExactSynonym
    base_uri:
      - http://purl.obolibrary.org/obo/PRIDE_
    hierarchical_property:
      - http://purl.obolibrary.org/obo/pride_cv.obo#part_of
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride_cv.obo

## BTO overide

  - id: ncbitaxon
    is_foundry: true
    ontology_purl: http://purl.obolibrary.org/obo/ncbitaxon.owl
    reasoner: NONE

## ReXo

  - id: rexo
    preferredPrefix: ReXO
    title: Regulation of Gene Expression Ontology
    uri: http://www.bio.ntnu.no/ontology/ReXO/rexo.owl
    description: "Regulation of Gene Expression"
    homepage: http://www.semantic-systems-biology.org/apo
    mailing_list: vladimir.n.mironov@gmail.com
    label_property: http://www.w3.org/2004/02/skos/core#prefLabel
    definition_property:
      - http://www.w3.org/2004/02/skos/core#definition
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    base_uri:
      - http://purl.obolibrary.org/obo/ReXO_
    oboSlims: true
    ontology_purl : http://www.bio.ntnu.no/ontology/ReXO/rexo.owl   ### This is the download URL

## molecular interaction

  - id: mi
    is_foundry: true
    ontology_purl: http://purl.obolibrary.org/obo/mi-test.owl
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050

#  - id: mondo
#    ontology_purl: http://purl.obolibrary.org/obo/mondo.owl
#    reasoner: EL
#
#  - id: upheno
#    is_foundry: true
#    ontology_purl: https://raw.githubusercontent.com/obophenotype/upheno/master/upheno.owl
#    reasoner: EL
