= FAQs

== Frequently Asked Questions


<<Why has the Catalog moved to the EBI?>>


<<Is there any way I can stay informed about new search features and developments?>>


<<How should I cite the GWAS Catalog?>>


<<Why does the data I just downloaded look different from what I downloaded in the old Catalog?>>


<<How do I do a search?>>


<<What can I type into the search bar?>>


<<What is the difference between a reported trait and a mapped trait?>>


<<Can I limit my search to a specific type of field such as author?>>


<<What is the difference between the blue links and the brown links?>>


<<When I search for a certain trait why are other traits returned?>>


<<Can I search for multiple or compound traits?>>


<<Why did my search return no results even though I am sure there used to be a trait like this in the Catalog?>>


<<How do I filter my results by p-value?>>


<<How do I filter my results by odds ratio?>>


<<How do I filter my results by beta coefficient?>>


<<How do I filter my results by date?>>


<<What happens to the count values for my search if I apply a filter?>>


<<What is the difference between filtering by a trait via the trait dropdown and doing a search by clicking on that trait in the results?>>


<<Why are some columns sortable and other are not?>>


<<Why did nothing happen when I tried sorting a column?>>


'''
== General


==== Why has the Catalog moved to the EBI?

From September 2010 to the present delivery and development of the Catalog has been a collaborative project between EMBL-EBI and NHGRI. In March 2015 the Catalog infrastructure moved to EMBL-EBI to enable delivery of an improved user interface, including ontology driven Catalog searching, and new curatorial infrastructure, supporting improved QC processes. Content available from www.genome.gov/gwastudies/ was last updated 20 Februry 2015 and is now frozen, no further updated content will be available at the NHGRI site. Updated content is available from www.ebi.ac.uk/GWAS/ and will be updated. The download file is now available from link:../api/search/downloads/full[here] and has updated content.

==== Is there any way I can stay informed about new search features and developments?

You can subscribe to our announcement list by sending an e-mail to gwas-announce-join@ebi.ac.uk with subject heading "subscribe". Traffic on this list will be limited to important announcements only so you don't need to worry about getting bombarded with loads of emails. For queries and user discussion, we have separate mailing lists, gwas-info@ebi.ac.uk to contact the Catalog team and gwas-users@ebi.ac.uk for user discussion (subscribe by emailing gwas-users-join@ebi.ac.uk with subject heading "subscribe").

==== How should I cite the GWAS Catalog?
Please see the link:about[About] page for citation guidance.

==== Why does the data I just downloaded look different from what I downloaded in the old Catalog?

A number of link:known-issues[known issues] got into the data during the migration. We are working hard to resolve these. Due to the way we now process the Catalog data for the full download, you may find that your spreadsheet has more rows than it did previously as each association between a SNP and a reported gene now gets its own row, i.e. if an association has several author-reported genes, it will be split across as many rows as there are genes.



== Searching

==== How do I do a search?
Type the thing you are interested in e.g. “breast cancer” into the search box and hit return or click the search icon.

==== What can I type into the search bar?
You can type any text you wish into the search bar. This will then return any exact string matches within a number of data fields in the Catalog, including title, author, journal, reported trait, mapped (ontology) trait, mapped trait's synonyms, mapped trait's parents, sample descriptions, genes and SNPs. 

==== What is the difference between a reported trait and a mapped trait?
Each study is assigned a trait description that best represents the phenotype under investigation. This is known as the reported trait as it is taken from the study publication. All reported traits are mapped to terms from the http://www.ebi.ac.uk/efo[Experimental Factor Ontology] resulting in one or more mapped traits. For more information about how ontologies are used in the catalog see our link:ontology[ontology] page.

==== Can I limit my search to a specific type of field such as author?
At the moment, the main search only supports searching across all fields, so if your search term is for example "Parkinson", you will see results for Parkinson's disease as well as studies with a first author named Parkinson. We are working on an "advanced search" mode where you can limit your search to certain fields or search for specific combinations of fields. To be alerted as soon as this functionality becomes available, subscribe to our announcement list (see above for subscription instructions).

For now, if you would like to search for a specific study, you can search by Pubmed ID. To limit your search to a specific trait or set of traits, we would suggest doing a general search for that trait first, then filtering your results using the trait filter dropdown to the left of the search results. For example, following a search for "lupus", you can limit your search results to "Systemic lupus erythematosus" via the dropdown.

==== What is the difference between the blue links and the brown links?
Clicking on a term highlighted in blue (e.g. author, trait or rsID) performs a full new search for this term. Clicking on a little brown link icon next to a term takes you to an external page related to this term, e.g. Pubmed Central for studies or Ensembl for SNPs or genes.

==== When I search for a certain trait why are other traits returned?
The search algorithm searches across a number of fields including study titles, sample descriptions, reported traits, mapped (ontology) traits, mapped traits' synonyms and mapped traits' parents. If your search term is a match to any of these categories, that result will be returned. If you search for "metabolic disease" for example, you will see a number of reported traits mapped to ontology traits such as "type II diabetes mellitus" because metabolic disease is a parent of diabetes in the ontology. Equally, searching for "diabetes" will return some potentially unexpected results as the search returns studies that were carried out in a sample population of diabetics, so the term "diabetes" is matched in the sample description. Filtering via the trait dropdown allows you to exclude unwanted traits for now and a more refined "advanced search" mode is under development.

==== Can I search for multiple or compound traits?
Currently the search bar searches for the exact text match of the search term entered within a range of  Catalog fields and any related traits through the mapped ontology fields. For example if you type “Schizophrenia and bipolar disorder” in the search bar this will return the compound reported trait "Schizophrenia and bipolar disorder" and "schizophrenia" but not "bipolar disorder". True multiple trait searching is currently not possible but we are working hard to include this feature as soon as possible. For now, we would recommend searching by a more general trait, eg "schizophrenia", then selecting any desired compound traits from the trait filter dropdown.

==== Why did my search return no results even though I am sure there used to be a trait like this in the Catalog?
Our search functionality is currently unable to allow for typos or term variations, so if you accidentally type "beast cancer" instead of "breast cancer", you will not get any results. Equally, "metabolic disorder" won't return any results while "metabolic disease" will return loads. A browseable list of all reported traits as well as autocomplete functionality for the search box are coming soon. In the mean time, if you get stuck, we recommend varying your search term or searching for your term in http://www.ebi.ac.uk/efo[EFO] to get an idea of what other terms might be available.



== Filters


==== How do I filter my results by p-value?
To filter association results by p-value, enter a maximum p-value into the appropriate filter box. The input format is "mantissa"x 10^"exponent"^, e.g. 5 x 10^-8^.

==== How do I filter my results by odds ratio?
To filter association results by odds ratio, enter a minimum and/or maximum value into the to and/or from box. You do not need to enter values in both boxes, so if you want values greater than your threshold, only enter a number into the from box or if you want values smaller than your threshold, only enter a number into the to box. The default minimum is 1 and you cannot search for values smaller than this.

==== How do I filter my results by beta coefficient?
Filtering by beta coefficient works exactly the same as filtering by odds ratio, although you can also search for values between 0 and 1.

==== How do I filter my results by date?
Filtering by date follows the same pattern as following by OR or beta coefficient. You can enter from and to dates to create a range or just a from date for all studies published since that day or just a to date for all studies published prior to that date.

==== What happens to the count values for my search if I apply a filter?
If you apply a filter to search results the count values will change to reflect the impact of applying the filter. Applying a filter will return a smaller subset of results. For example, at present, if I run a search for the term "asthma" it returns 223 associations. If I apply a p-value filter of 6e-8 the number of associations is now shown as 74.

==== What is the difference between filtering by a trait via the trait dropdown and doing a search by clicking on that trait in the results?
Filtering via the trait dropdown limits the search results to studies that have the selected trait(s) as their reported trait, as well as any associations identified in those studies. Clicking on a trait link does a complete new search for that term, searching across all fields, including title and sample descriptions, so you may get additional results, not just studies annotated with the search trait.


== Sorting

==== Why are some columns sortable and other are not?
Because of the way our search algorithm works, some fields can't be sorted at the moment. We are trying to find a workaround for this. For now, if you really need to sort by an unsortable column, we would recommend downloading the results into a spreadsheet and sorting them that way.

==== Why did nothing happen when I tried sorting a column?
Some fields contains results that don't work well with our sorting algorithm. When this happens, rather than introduce a glitch into your results, the table will simply refuse the sort. This is a known issue and we are looking for a way to fix it.

'''

==== Got a question that isn't answered here?
Email us at gwas-info@ebi.ac.uk.
