= OLS Documentation
:doctype: book
:toc: left
:toc-title: OLS Documentation
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs


== Misson statement
The OLS aims to be a comprehensive collection of biomedical ontologies for the life sciences.

== Description of the service
The Ontology Lookup Service (OLS) is a repository for bioinformatic ontologies that aims to provide a single point of access to the latest ontology versions. The user can browse the ontologies through the website as well as programmatically through the API. The new version of the OLS, which you are browsing at the moment, is meant to replace the old version that was online for nearly 10 years. To see a more detailed timeline of the transition and how to migrate for the old version to the new OLS,  please check the roadmap (http://www.ebi.ac.uk/ols/beta/roadmap.html).

== How to use the website
There are two main ways of browsing the OLS:
Browse by ontology: By clicking on the ontology on the main page. The user enters the ontology on top level and is able to browse through the tree view to lower levels
Search by term: Use the search box to enter the term that you are looking for. The provided results show all ontologies where the term was found. By using the advanced search the user can further restrict the results to one or multiple ontologies or to a specific 'type'. Types can be class, property or individual.
Using the advanced search you can restrict searches to one or more ontology

No matter what way of browsing an ontology you choose, your search leads you to the view of a term

== Contact
* For feedback, enquiries or suggestion about OLS or to request a new ontology please contact ols-support
* For bugs or problems with the code or API please create a GitHub issue (https://github.com/EBISPOT/OLS)

== License
Apache version 2.0 (link to license in github). See also EBI term of use http://www.ebi.ac.uk/about/terms-of-use

== Resources

=== OLS source code

* You can obtain the source code at https://github.com/EBISPOT/OLS

=== OLS REST API
* Information about the API access to our services can be found at (http://www.ebi.ac.uk/ols/beta/docs/api)

=== OLS javascript widgets
* Links to different OLS widgets (coming soon)

=== Local OLS installation
* Details on how to build a local OLS can be found link:../docs/installation-guide[here]

=== Neo4J schema

* link:../docs/neo4j-schema[Description of the OLS Neo4J schema]
* link:https://github.com/EBISPOT/OLS/tree/master/ols-apps/ols-neo4j-app[How to build a standalone Neo4J index for an ontology]

=== SOLR schema
* link:solr-schema[Description of the OLS SOLR schema]
* link:https://github.com/EBISPOT/OLS/tree/master/ols-apps/ols-solr-app[How to build a standalone SOLR index for an ontology]


== FAQ

* How can I ask for a certain ontology to be included in OLS? +
e-mail ols-support@ebi.ac.uk or open a github issue
* What ontology formats does OLS support? +
OBO and OWL 2
* What reasoners are supported by OLS? +
Hermit and ELK
* How does OLS handle OWL imports? +
OWL imports are respects so any impoprted files will be indexes as part of the ontology. If any import fails these will be ignored
* How often does OLS check for updates in external ontology files? +
OLS updates nightly to always provide the latest ontology versions
* How can I use OLS in my own applications? +
The use of OLS for applications is widely supported by the API, which allows you to retrieve exactly the data you need. Check the API section for more information. In addition, some specific functionality (graphview, treeview, autocomplete) of OLS is available as stand alone widget and can be easily integrated into other websites.
* What is the Neo4J schema? +
See the OLS schema documentation here
* What is the SOLR schema? +
See the OLS schema documentation here
* How can I build a local version of OLS? ? +
See the documentation here
* How can I build a standalone SOLR server for an ontology? +
See the documentation here
* How can I build a standalone Neo4J server for an ontology? +
See the documentation here
