== OLS Documentation

=== What are you looking for?

link:website[Website documentation]:: Documentation on how to use the OLS website
link:developer[Developer documentation]:: Documentation for developers including how to use the OLS REST API, how to use the OLS widgets and how to install a local OLS

== FAQ

* How can I ask for a certain ontology to be included in OLS? +
e-mail ols-support@ebi.ac.uk or open a github issue
* What ontology formats does OLS support? +
OBO and OWL 2
* What reasoners are supported by OLS? +
Hermit and ELK
* How does OLS handle OWL imports? +
OWL imports are respects so any impoprted files will be indexes as part of the ontology. If any import fails these will be ignored
* How often does OLS check for updates in external ontology files? +
OLS updates nightly to always provide the latest ontology versions
* How can I use OLS in my own applications? +
The use of OLS for applications is widely supported by the API, which allows you to retrieve exactly the data you need. Check the API section for more information. In addition, some specific functionality (graphview, treeview, autocomplete) of OLS is available as stand alone widget and can be easily integrated into other websites.
* What is the Neo4J schema? +
See the OLS schema documentation here
* What is the SOLR schema? +
See the OLS schema documentation here
* How can I build a local version of OLS? ? +
See the documentation here
* How can I build a standalone SOLR server for an ontology? +
See the documentation here
* How can I build a standalone Neo4J server for an ontology? +
See the documentation here
